### ISSUE TITLE
Wartungsarbeiten Sektionsportal / Tocco, 12. Dezember 2021

### ISSUE THREAD

**Issue by spschweiz** [spschweiz/status#13]
Am Dienstag, 14. Dezember steht das Sektionsportal und Tocco nicht zur Verfügung, da wir auf eine neue Version von Tocco wechseln. Die Arbeiten beginnen ca. um 8:00 und dauern voraussichtlich bis in den den späten Nachmittag.

**Comment by anweibel** [comment]
Am Dienstag, 14. Dezember steht das Sektionsportal und Tocco nicht zur Verfügung, da wir auf eine neue Version von Tocco wechseln. Die Arbeiten beginnen ca. um 8:00 und dauern voraussichtlich bis in den den späten Nachmittag.

**Comment by anweibel** [comment]
Der Releasewechsel ist den Erwartungen entsprechend gut unterwegs und bisher gibt es keine technischen Schwierigkeiten. Wir melden uns mit einem neuen Zwischenstand um +/- 15.30h.
